services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: c8yhub
    ports:
      - "5433:5433"
    volumes:
      - c8yhub_db_data:/var/lib/postgresql/data
  app:
    image: cpmiras/c8yhub:latest
    platform: linux/amd64
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5433/c8yhub"

volumes:
  c8yhub_db_data:
